x-common:
  database: &db-environment
    #
    # Do not remove the "&db-password" from the line below.
    MYSQL_PASSWORD: &db-password 'CHANGE_ME'
    MYSQL_ROOT_PASSWORD: 'CHANGE_ME_TOO'
    # ^^^ The following values will be
    #     changed in the following commands
  panel: &panel-environment
    #
    # Change this to your panel URL
    APP_URL: 'https://panel.kunet.dev'

    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: 'UTC'
    APP_SERVICE_AUTHOR: 'noreply@example.com'
  # Not strictly necessary unless you need to send mail.
  mail: &mail-environment
    MAIL_FROM: 'noreply@example.com'
    MAIL_DRIVER: 'smtp'
    MAIL_HOST: 'mail'
    MAIL_PORT: '1025'
    MAIL_USERNAME: ''
    MAIL_PASSWORD: ''
    MAIL_ENCRYPTION: 'true'

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    restart: always
    networks:
      - caddy
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './pterodactyl/database:/var/lib/mysql'
    environment:
      <<: *db-environment
      MYSQL_DATABASE: 'panel'
      MYSQL_USER: 'pterodactyl'
  cache:
    image: redis:alpine
    restart: always
    networks:
      - caddy
  panel:
    networks:
      - caddy
    image: ghcr.io/pterodactyl/panel:latest
    container_name: panel
    restart: always
    links:
      - database
      - cache
    volumes:
      - './pterodactyl/var/:/app/var/'
      - './pterodactyl/nginx/:/etc/nginx/http.d/'
      - './pterodactyl/certs/:/etc/letsencrypt/'
      - './pterodactyl/logs/:/app/storage/logs'
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: 'production'
      APP_ENVIRONMENT_ONLY: 'false'
      CACHE_DRIVER: 'redis'
      SESSION_DRIVER: 'redis'
      QUEUE_DRIVER: 'redis'
      REDIS_HOST: 'cache'
      DB_HOST: 'database'
      DB_PORT: '3306'
networks:
  caddy:
    external: true
    name: caddy
    driver: bridge
